name: CI
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm run format:check
      - run: npm lint
      - run: npm run jest
      - run: npm run cypress